version: '3.8'
services:
    redis:
        image: redislabs/redismod
        restart: always
        ports:
          - "6379:6379"
        volumes:
          - cache:/data
        command: --dir /data --loadmodule /usr/lib/redis/modules/redistimeseries.so
volumes:
  cache:
    driver: local
    
